import type { Metadata } from 'next';
import './globals.css';
import 'simplebar-react/dist/simplebar.min.css';
import Navbar from './_components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className="container relative h-full pt-10">{children}</div>
    </>
  );
}
