import type { Metadata } from 'next';
import './globals.css';
import 'simplebar-react/dist/simplebar.min.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="fixed z-10 h-10 w-full bg-slate-100">
        <div className="container">navbar</div>
      </div>
      <div className="container relative h-full pt-10">{children}</div>
    </>
  );
}
